CREATE TABLE EMP_DDP(
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIRE_DATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
);
DESC EMP_DDP;

RENAME EMP_ALTER TABLE TO EMP_DDL; 
RENAME EMP_DDP TO EMP_ALTER;
SELECT*FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD (HP VARCHAR2(20));
SELECT*FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;
SELECT*FROM EMP_ALTER;
ALTER TABLE EMP_ALTER
RENAME COLUMN 전화번호 TO TEL;

ALTER TABLE EMP_ALTER
MODIFY(EMPNO NUMBER(5) );
DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;
SELECT*FROM EMP_ALTER;


DROP TABLE EMP_ALTER;
DESC EMP_ALTER;

CREATE TABLE EMP
CREATE INDEX members_last_name_i  -- 인덱스 이름
ON members(last_name);

CREATE INDEX IDX_EMP_SAL
ON EMP(SAL);
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

SELECT 
      TABLE_NAME                테이블명,
      INDEX_NAME                인덱스이름,
      COLUMN_NAME            컬럼이름
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME = 'EMP';

SELECT 
TABLE_NAME 테이블명,
INDEX_NAME 인덱스이름,
COLUMN_NAME 컬럼이름
FROM USER_IND_COLUMNS
WHERE TABLE_NAME='EMP';

DROP INDEX IDX_EMP_SAL;

CREATE VIEW VW_EMP20
AS
SELECT EMPNO 사원번호,ENAME 사원이름,JOB 직책,DEPTNO 부서번호
FROM EMP;

DROP VIEW VW_EMP20;

CREATE TABLE DEPT_SEQUENCE
AS SELECT*
FROM DEPT
WHERE 1<>1;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_SEQUENCE';

ALTER SEQUENCE DEPT_SEQUENCE
INCREMENT BY 10;
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
START WITH 10
INCREMENT BY 10;

SELECT*FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='SEQ_DEPT_SEQUENCE';

INSERT INTO DEPT_SEQUENCE(DEPTNO,DENAME,LOC)VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL'DATABAS','SEOUL');

SELECT*FROM DEPT_SEQUENCE;


INSERT INTO DEPT_SEQUENCE   VALUES ( SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE','SEOUL');
SELECT*FROM DEPT_SEQUENCE;

SELECT DEPT_SEQUENCE.CURRVAL FROM DUAL;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL; 

DROP SEQUENCE SEQ_DEPT_SEQUENCE;